### ISSUE TITLE
Update build instructions in README

### ISSUE THREAD

**Issue by TimLovesTech** [j00ch/linux-ck-autobuild#1]
> git clone https://aur.archlinux.org/packages/linux-ck-autobuild

Should be

> git clone https://aur.archlinux.org/linux-ck-autobuild.git

AUR wiki entry states this format as well -

> - Clone its git repository, labeled "Git Clone URL" in the "Package Details" on its AUR page. This is the preferred method, an advantage of which is that you can easily get updates to the package via git pull.

> $ git clone https://aur.archlinux.org/package_name.git

**Comment by j00ch** [comment]
Whoops, thanks for catching that one. Was a bit too quick with the copy/paste button there :grin:
